name: deploy jekyll algolia
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  algolia:
    env:
      ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: set up env
        run: |
          cd docs
          bundle install

      - name: jekyll algolia
        run: |
          cd docs
          ALGOLIA_API_KEY=$ALGOLIA_API_KEY bundle exec jekyll algolia
